Repository Auctionable-Change/auctionable_change, pull requests merged in 2020-07, with the labels that each got.

#24 Feature/navigation
  App.js
  package-lock.json
  package.json
  screens/CurrentListings.js
  screens/ListingDetails.js
  screens/PurchaseItem.js
  screens/Welcome.js
Labels: Buyer X, FE, Project Setup, enhancement

#32 Feature/currentlistings
  mockData/mockListings.js
  package-lock.json
  package.json
  screens/CurrentListings.js
  screens/grill.jpg
Labels: FE

#36 Listing details
  screens/ListingDetails.js
Labels: Buyer X, FE, enhancement

#46 Seller listing
  App.js
  screens/PostItem.js
Labels: FE, Seller X

#55 Feature/registeritempost
  screens/ChooseCharity.js
  screens/PostConfirmation.js
  screens/apiCalls.js
  store.js
Labels: FE, User Story
